default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: localhost

development:
  <<: *default
  database: sell_control_development

test:
  <<: *default
  database: sell_control_test

production:
  <<: *default
  database: sell_control_production
  username: sell_control
  password: <%= ENV['SELL_CONTROL_DATABASE_PASSWORD'] %>
